// invistaix-frontend/src/components/layout/Sidebar.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { 
  LayoutDashboard, 
  Home,
  Users, 
  UserPlus, 
  DollarSign, 
  BarChart3,
  Settings,
  LogOut
} from 'lucide-react';

const Sidebar = () => {
  const location = useLocation();
  const { logout } = useAuth();
  
  const menuItems = [
    { 
      title: "Dashboard", 
      path: "/dashboard", 
      icon: <LayoutDashboard className="h-5 w-5" /> 
    },
    { 
      title: "Imóveis", 
      path: "/dashboard/imoveis", 
      icon: <Home className="h-5 w-5" /> 
    },
    { 
      title: "Proprietários", 
      path: "/dashboard/proprietarios", 
      icon: <Users className="h-5 w-5" /> 
    },
    { 
      title: "Gestores", 
      path: "/dashboard/gestores", 
      icon: <UserPlus className="h-5 w-5" /> 
    },
    { 
      title: "Financeiro", 
      path: "/dashboard/financeiro", 
      icon: <DollarSign className="h-5 w-5" /> 
    },
    { 
      title: "Performance", 
      path: "/dashboard/performance", 
      icon: <BarChart3 className="h-5 w-5" /> 
    }
  ];

  const handleLogout = () => {
    logout();
    toast.success('Logout realizado com sucesso!');
  };
  
  return (
    <aside className="bg-sidebar w-64 min-h-screen flex flex-col fixed left-0 top-0 bottom-0 z-30 shadow-lg">
      <div className="p-4">
        <div className="flex items-center justify-center md:justify-start">
          <span className="text-sidebar-foreground text-2xl font-bold">InvistaIX</span>
        </div>
      </div>
      
      <nav className="mt-6 flex-1">
        <ul className="space-y-1 px-2">
          {menuItems.map((item, index) => (
            <li key={index}>
              <Link
                to={item.path}
                className={cn(
                  "flex items-center px-4 py-3 text-sm rounded-md transition-colors",
                  location.pathname === item.path
                    ? "bg-sidebar-accent text-sidebar-primary font-medium"
                    : "text-sidebar-foreground hover:bg-sidebar-accent/50"
                )}
              >
                {item.icon}
                <span className="ml-3">{item.title}</span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>

      <div className="p-4 border-t border-sidebar-border">
        <Link
          to="/dashboard/configuracoes"
          className={cn(
            "flex items-center px-4 py-3 text-sm rounded-md transition-colors mb-2",
            location.pathname === "/dashboard/configuracoes"
              ? "bg-sidebar-accent text-sidebar-primary font-medium"
              : "text-sidebar-foreground hover:bg-sidebar-accent/50"
          )}
        >
          <Settings className="h-5 w-5" />
          <span className="ml-3">Configurações</span>
        </Link>
        <button 
          onClick={handleLogout}
          className="w-full flex items-center px-4 py-3 text-sm rounded-md transition-colors text-sidebar-foreground hover:bg-sidebar-accent/50"
        >
          <LogOut className="h-5 w-5" />
          <span className="ml-3">Sair</span>
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;

// invistaix-frontend/src/components/SideBar.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import { Menu, X, LayoutDashboard, CheckCircle, Home, Users, Briefcase, DollarSign, BarChart2, FileText, User } from 'lucide-vue-next';

const isSidebarOpen = ref(false);
const isDesktop = ref(window.innerWidth >= 768);
const userPermissions = ref([
  'dashboard',
  'vistorias',
  'imoveis',
  'proprietarios',
  'gestores',
  'financeiro',
  'performance',
  'relatorios'
]);

function toggleSidebar() {
  isSidebarOpen.value = !isSidebarOpen.value;
}

function hasPermission(section: string) {
  return userPermissions.value.includes(section);
}

// Atualiza o estado da sidebar com base no tamanho da janela
function updateSidebarState() {
  const wasDesktop = isDesktop.value;
  isDesktop.value = window.innerWidth >= 768;
  if (!wasDesktop && isDesktop.value) {
    isSidebarOpen.value = true;
  } else if (wasDesktop && !isDesktop.value) {
    isSidebarOpen.value = false;
  }
}

const sidebarClasses = computed(() => ({
  'sidebar text-white w-64 min-h-screen p-4': true,
  'fixed top-0 left-0 h-full md:static': true,
  'sidebar-hidden': !isSidebarOpen.value && !isDesktop.value
}));

onMounted(() => {
  updateSidebarState();
  window.addEventListener('resize', updateSidebarState);
});

onBeforeUnmount(() => {
  window.removeEventListener('resize', updateSidebarState);
});
</script>

<template>
  <div class="flex">
    <!-- Sidebar -->
    <aside :class="sidebarClasses" style="background-color: #000000;">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-xl font-bold">InvistaIX</h2>
        <button @click="toggleSidebar" class="text-white focus:outline-none md:hidden">
          <X class="w-6 h-6" />
        </button>
      </div>
      <nav>
        <ul>
          <li v-if="hasPermission('dashboard')" class="mb-4">
            <a href="#" class="flex items-center p-2 bg-green-700 rounded">
              <LayoutDashboard class="w-5 h-5 mr-2" />
              Dashboard
            </a>
          </li>
          <li v-if="hasPermission('vistorias')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <CheckCircle class="w-5 h-5 mr-2" />
              Vistorias
            </a>
          </li>
          <li v-if="hasPermission('imoveis')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <Home class="w-5 h-5 mr-2" />
              Imóveis
            </a>
          </li>
          <li v-if="hasPermission('proprietarios')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <Users class="w-5 h-5 mr-2" />
              Proprietários
            </a>
          </li>
          <li v-if="hasPermission('gestores')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <Briefcase class="w-5 h-5 mr-2" />
              Gestores
            </a>
          </li>
          <li v-if="hasPermission('financeiro')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <DollarSign class="w-5 h-5 mr-2" />
              Financeiro
            </a>
          </li>
          <li v-if="hasPermission('performance')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <BarChart2 class="w-5 h-5 mr-2" />
              Performance
            </a>
          </li>
          <li v-if="hasPermission('relatorios')" class="mb-4">
            <a href="#" class="flex items-center p-2 hover:bg-gray-700 rounded">
              <FileText class="w-5 h-5 mr-2" />
              Relatórios
            </a>
          </li>
        </ul>
      </nav>
    </aside>

		<!-- Header -->
    <div class="flex-1 flex flex-col">
      <header class="p-4 flex justify-between items-center" style="background-color: #ffffff; color: #000000;">
        <button @click="toggleSidebar" class="focus:outline-none md:hidden">
          <Menu class="w-6 h-6" />
        </button>
        <div class="flex-1"></div>
        <button class="focus:outline-none">
          <User class="w-6 h-6" />
        </button>
      </header>

      <!-- Slot for content -->
      <main class="flex-1">
        <slot />
      </main>
    </div>
  </div>
</template>

<style scoped>
.sidebar {
  transition: transform 0.3s ease-in-out;
}
.sidebar-hidden {
  transform: translateX(-100%);
}
header {
  border-bottom: 1px solid rgb(0, 0, 0, 0.1);
}
</style>
